/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculride.view;

import com.mycompany.faculride.controller.AvaliacaoController;
import com.mycompany.faculride.model.Avaliacao;
import javax.swing.JOptionPane;

/**
 *
 * @author livia
 */
public class FormAvaliacao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAvaliacao.class.getName());
    private static FormAvaliacao FormAvaliacaoUnico;

    
    private FormAvaliacao() {
        initComponents();
    }

    
    // MÉTODO SINGLETON
    public static FormAvaliacao getFormAvaliacao() {
        if (FormAvaliacaoUnico == null) {
            FormAvaliacaoUnico =
            new FormAvaliacao();
        }
        return FormAvaliacaoUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblText = new javax.swing.JLabel();
        LblMotorista = new javax.swing.JLabel();
        BoxAvaliar = new javax.swing.JComboBox<>();
        LblLogo = new javax.swing.JLabel();
        BtAvaliar = new javax.swing.JButton();
        LblHome = new javax.swing.JLabel();
        BtHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblText.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        LblText.setText("Avalie AQUI! ★");

        LblMotorista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblMotorista.setText("Motorista: ");

        BoxAvaliar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ★", "2 ★", "3 ★", "4 ★", "5 ★" }));
        BoxAvaliar.addActionListener(this::BoxAvaliarActionPerformed);

        LblLogo.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        LblLogo.setForeground(new java.awt.Color(102, 102, 255));
        LblLogo.setText("FaculRide🚗");

        BtAvaliar.setBackground(new java.awt.Color(204, 204, 255));
        BtAvaliar.setText("Avaliar");
        BtAvaliar.addActionListener(this::BtAvaliarActionPerformed);

        LblHome.setText("Volte para a tela inicial...");

        BtHome.setBackground(new java.awt.Color(204, 204, 255));
        BtHome.setText("Home");
        BtHome.addActionListener(this::BtHomeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BoxAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(LblText))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(BtAvaliar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(BtHome)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LblLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(LblText)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoxAvaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMotorista))
                .addGap(40, 40, 40)
                .addComponent(BtAvaliar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtHome)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxAvaliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxAvaliarActionPerformed

    private void BtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeActionPerformed
        FormTelaHome.getFormTelaHome().setVisible(true);
    }//GEN-LAST:event_BtHomeActionPerformed

    private void BtAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAvaliarActionPerformed
        avaliarMotorista();
    }//GEN-LAST:event_BtAvaliarActionPerformed
private void avaliarMotorista() {

    Avaliacao avaliacao =
    new Avaliacao();


    avaliacao.setNota(
        Integer.parseInt(
            BoxAvaliar.getSelectedItem()
            .toString()
        )
    );


    AvaliacaoController controller =
    new AvaliacaoController();


    controller.avaliarMotorista(
        avaliacao
    );


    JOptionPane.showMessageDialog(
        null,
        "Avaliação enviada!"
    );

}
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxAvaliar;
    private javax.swing.JButton BtAvaliar;
    private javax.swing.JButton BtHome;
    private javax.swing.JLabel LblHome;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JLabel LblMotorista;
    private javax.swing.JLabel LblText;
    // End of variables declaration//GEN-END:variables
}
