/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculride.view;

import com.mycompany.faculride.controller.CaronaController;
import com.mycompany.faculride.controller.SolicitacaoController;
import com.mycompany.faculride.model.Carona;
import com.mycompany.faculride.model.Solicitacao;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.sessao;
import com.mycompany.faculride.view.FormAvaliacao;
import connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author livia
 */
public class FormSolicitacoes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSolicitacoes.class.getName());
    private static FormSolicitacoes FormSolicitacoesUnico;

    
    private FormSolicitacoes() {
        initComponents();
        carregarTabela();
        carregarTabelaEnviadas();
    }
    // Sobreescrita carregar tabela
    @Override
public void setVisible(boolean visible) {

    if (visible) {

        carregarTabela();
        carregarTabelaEnviadas();

    }

    super.setVisible(visible);
}
    
    // MÉTODO SINGLETON
    public static FormSolicitacoes getFormSolicitacoes() {
        if (FormSolicitacoesUnico == null) {
            FormSolicitacoesUnico =
            new FormSolicitacoes();
        }
        return FormSolicitacoesUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        LblLogo = new javax.swing.JLabel();
        TabbedPane1 = new javax.swing.JTabbedPane();
        Panel2 = new javax.swing.JPanel();
        ScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BtAvaliar = new javax.swing.JButton();
        BtAvaliar1 = new javax.swing.JButton();
        Panel1 = new javax.swing.JPanel();
        ScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BtAceitar = new javax.swing.JButton();
        BtRecusar = new javax.swing.JButton();
        BtRecusar1 = new javax.swing.JButton();
        LblInicio = new javax.swing.JLabel();
        BtHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblLogo.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        LblLogo.setText("Minhas solicitações ✉");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Motorista", "Origem", "Destino", "horário", "Valor", "Status"
            }
        ));
        ScrollPane1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(6).setResizable(false);
        }

        BtAvaliar.setBackground(new java.awt.Color(204, 204, 255));
        BtAvaliar.setText("Avaliar");
        BtAvaliar.addActionListener(this::BtAvaliarActionPerformed);

        BtAvaliar1.setBackground(new java.awt.Color(204, 204, 255));
        BtAvaliar1.setText("Cancelar Solicitação");
        BtAvaliar1.addActionListener(this::BtAvaliar1ActionPerformed);

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(BtAvaliar)
                .addGap(108, 108, 108)
                .addComponent(BtAvaliar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAvaliar)
                    .addComponent(BtAvaliar1))
                .addContainerGap())
        );

        TabbedPane1.addTab("Enviadas", Panel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Solicitação", "Id Carona", "Passageiro", "Origem", "Destino", "Horário", "Valor", "Status"
            }
        ));
        ScrollPane2.setViewportView(jTable1);

        BtAceitar.setBackground(new java.awt.Color(204, 204, 255));
        BtAceitar.setText("Aceitar");
        BtAceitar.addActionListener(this::BtAceitarActionPerformed);

        BtRecusar.setBackground(new java.awt.Color(204, 204, 255));
        BtRecusar.setText("Recusar");
        BtRecusar.addActionListener(this::BtRecusarActionPerformed);

        BtRecusar1.setBackground(new java.awt.Color(204, 204, 255));
        BtRecusar1.setText("Marcar Como Lotada");
        BtRecusar1.addActionListener(this::BtRecusar1ActionPerformed);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(BtAceitar)
                .addGap(47, 47, 47)
                .addComponent(BtRecusar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtRecusar1)
                .addGap(53, 53, 53))
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addComponent(ScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAceitar)
                    .addComponent(BtRecusar)
                    .addComponent(BtRecusar1))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        TabbedPane1.addTab("Recebidas", Panel1);

        LblInicio.setText("Volte para a tela inicial...");

        BtHome.setBackground(new java.awt.Color(204, 204, 255));
        BtHome.setText("Home");
        BtHome.addActionListener(this::BtHomeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(TabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(LblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(BtHome)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtHome)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeActionPerformed
        FormTelaHome.getFormTelaHome().setVisible(true);
    }//GEN-LAST:event_BtHomeActionPerformed

    private void BtAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAvaliarActionPerformed
        abrirTelaAvaliacao();
    }//GEN-LAST:event_BtAvaliarActionPerformed

    private void BtAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAceitarActionPerformed
        aceitarSolicitacao();
    }//GEN-LAST:event_BtAceitarActionPerformed

    private void BtRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRecusarActionPerformed
        recusarSolicitacao();
    }//GEN-LAST:event_BtRecusarActionPerformed

    private void BtRecusar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRecusar1ActionPerformed
        marcarComoLotada();
    }//GEN-LAST:event_BtRecusar1ActionPerformed

    private void BtAvaliar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAvaliar1ActionPerformed
        excluirSolicitacao();        
    }//GEN-LAST:event_BtAvaliar1ActionPerformed
    private void carregarTabela() {

    DefaultTableModel modelo =
        (DefaultTableModel)
        jTable1.getModel();

    modelo.setRowCount(0);

    SolicitacaoController controller =
        new SolicitacaoController();

    try {
System.out.println(
    "Usuário logado: "
    + sessao.usuarioLogado.getNome()
);
        ResultSet rs =
            controller
            .listarSolicitacoesRecebidas(
                sessao.usuarioLogado
                .getNome()
            );

        while (rs.next()) {

          modelo.addRow(
    new Object[] {
        rs.getInt("id"),
        rs.getInt("id_carona"),
        rs.getString("passageiro"),
        rs.getString("origem"),
        rs.getString("destino"),
        rs.getString("horario"),
        rs.getDouble("valor"),
        rs.getString("status")
    }
);
        }

    } catch (Exception e) {

        e.printStackTrace();
    }
}
    private void carregarTabelaEnviadas() {

    DefaultTableModel modelo =
        (DefaultTableModel)
        jTable2.getModel();

    modelo.setRowCount(0);

    SolicitacaoController controller =
        new SolicitacaoController();

    try {

        ResultSet rs =
            controller.listarSolicitacoesEnviadas(
                sessao.usuarioLogado.getNome()
            );

        while (rs.next()) {

            modelo.addRow(
                new Object[] {
                    rs.getInt("id"),
                    rs.getString("motorista"),
                    rs.getString("origem"),
                    rs.getString("destino"),
                    rs.getString("horario"),
                    rs.getDouble("valor"),
                    rs.getString("status")
                }
            );
        }

    } catch (Exception e) {

        e.printStackTrace();
    }
}
    
    private void aceitarSolicitacao() {

    int linha =
        jTable1.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
            null,
            "Selecione uma solicitação!"
        );

        return;
    }

    int idSolicitacao =
        Integer.parseInt(
            jTable1.getValueAt(
                linha,
                0
            ).toString()
        );

    Solicitacao solicitacao =
        new Solicitacao();

    solicitacao.setId(
        idSolicitacao
    );

    SolicitacaoController controller =
        new SolicitacaoController();

    controller.aceitarSolicitacao(
        solicitacao
    );

    JOptionPane.showMessageDialog(
        null,
        "Solicitação aceita!"
    );

    carregarTabela();
}
    private void recusarSolicitacao() {

    int linha =
        jTable1.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
            null,
            "Selecione uma solicitação!"
        );

        return;
    }

    int idSolicitacao =
        Integer.parseInt(
            jTable1.getValueAt(
                linha,
                0
            ).toString()
        );

    Solicitacao solicitacao =
        new Solicitacao();

    solicitacao.setId(
        idSolicitacao
    );

    SolicitacaoController controller =
        new SolicitacaoController();

    controller.recusarSolicitacao(
        solicitacao
    );

    JOptionPane.showMessageDialog(
        null,
        "Solicitação recusada!"
    );

    carregarTabela();
}
    
  private void abrirTelaAvaliacao() {

    int linha =
        jTable2.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
            null,
            "Selecione uma solicitação!"
        );

        return;
    }

    String motorista =
        jTable2.getValueAt(
            linha,
            1
        ).toString();

    FormAvaliacao tela =
        FormAvaliacao.getFormAvaliacao();

    tela.setMotorista(
        motorista
    );

    tela.setVisible(
        true
    );
}
  private void marcarComoLotada() {

    int linha =
        jTable1.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
            null,
            "Selecione uma solicitação!"
        );

        return;
    }

    int idCarona =
        Integer.parseInt(
            jTable1.getValueAt(
                linha,
                1
            ).toString()
        );

    Carona carona =
        new Carona();

    carona.setId(
        idCarona
    );

    carona.setStatus(
        "Lotada"
    );

    CaronaController controller =
        new CaronaController();

    controller.atualizarStatus(
        carona
    );

    JOptionPane.showMessageDialog(
        null,
        "Carona marcada como lotada!"
    );
}
  private void excluirSolicitacao() {

    int linha =
        jTable2.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
            null,
            "Selecione uma solicitação!"
        );

        return;
    }
     int resposta =
        JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente cancelar esta solicitação?",
            "Confirmar Cancelamento",
            JOptionPane.YES_NO_OPTION
        );

    if (resposta != JOptionPane.YES_OPTION) {

        return;
    }

    int id =
        Integer.parseInt(
            jTable2.getValueAt(
                linha,
                0
            ).toString()
        );

    SolicitacaoController controller =
        new SolicitacaoController();

    controller.excluirSolicitacao(
        id
    );

    JOptionPane.showMessageDialog(
        null,
        "Solicitação cancelada!"
    );

    carregarTabelaEnviadas();
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAceitar;
    private javax.swing.JButton BtAvaliar;
    private javax.swing.JButton BtAvaliar1;
    private javax.swing.JButton BtHome;
    private javax.swing.JButton BtRecusar;
    private javax.swing.JButton BtRecusar1;
    private javax.swing.JLabel LblInicio;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane2;
    private javax.swing.JTabbedPane TabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
