/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculride.view;

/**
 *
 * @author livia
 */
public class FormTelaHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTelaHome.class.getName());

    /**
     * Creates new form FormTelaHome
     */
    public FormTelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        LblBem = new javax.swing.JLabel();
        LblLogo = new javax.swing.JLabel();
        LblAcoes = new javax.swing.JLabel();
        BtOferecer = new javax.swing.JButton();
        BtVer = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        Menu2 = new javax.swing.JMenu();
        Menu3 = new javax.swing.JMenu();
        Menu4 = new javax.swing.JMenu();
        Menu5 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblBem.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        LblBem.setText("Olá, Seja bem vindo");

        LblLogo.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        LblLogo.setForeground(new java.awt.Color(102, 102, 255));
        LblLogo.setText("FaculRide🚗");

        LblAcoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblAcoes.setText("Ações Rápidas:");

        BtOferecer.setForeground(new java.awt.Color(102, 102, 255));
        BtOferecer.setText("+  Oferecer Carona");
        BtOferecer.addActionListener(this::BtOferecerActionPerformed);

        BtVer.setForeground(new java.awt.Color(102, 102, 255));
        BtVer.setText("🔍 ver caronas disponiveis");
        BtVer.addActionListener(this::BtVerActionPerformed);

        Menu1.setBackground(new java.awt.Color(204, 204, 255));
        Menu1.setText("🏠 Home");
        MenuPrincipal.add(Menu1);

        Menu2.setText("👥 Oferecer Carona");
        MenuPrincipal.add(Menu2);

        Menu3.setText("🚗 Caronas disponíveis");
        MenuPrincipal.add(Menu3);

        Menu4.setText("✉️ Solicitações");
        MenuPrincipal.add(Menu4);

        Menu5.setText("★Avaliação");
        MenuPrincipal.add(Menu5);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblBem)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(LblAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(BtOferecer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(BtVer)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblBem)
                .addGap(34, 34, 34)
                .addComponent(LblAcoes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtOferecer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtVer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtOferecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtOferecerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtOferecerActionPerformed

    private void BtVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTelaHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtOferecer;
    private javax.swing.JButton BtVer;
    private javax.swing.JLabel LblAcoes;
    private javax.swing.JLabel LblBem;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenu Menu2;
    private javax.swing.JMenu Menu3;
    private javax.swing.JMenu Menu4;
    private javax.swing.JMenu Menu5;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    // End of variables declaration//GEN-END:variables
}
