/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculride.view;

import com.mycompany.faculride.controller.UsuarioController;
import com.mycompany.faculride.model.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import util.sessao;

/**
 *
 * @author livia
 */
public class FormTelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTelaLogin.class.getName());
    private static FormTelaLogin telaLoginUnica;
    /**
     * Creates new form FormTelaLogin
     */
    public FormTelaLogin() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    
     public static FormTelaLogin getFormTelaLogin() {
        if (telaLoginUnica == null) {
            telaLoginUnica = new FormTelaLogin();
        }
        return telaLoginUnica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormLogin = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        Text2 = new javax.swing.JTextField();
        LblSenha = new javax.swing.JLabel();
        Text1 = new javax.swing.JTextField();
        BtEntrar = new javax.swing.JButton();
        LblConta = new javax.swing.JLabel();
        BtCadastrar = new javax.swing.JButton();
        LblBem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FormLogin.setBackground(new java.awt.Color(204, 204, 255));
        FormLogin.setFont(new java.awt.Font("Serif", 2, 36)); // NOI18N
        FormLogin.setForeground(new java.awt.Color(102, 102, 255));
        FormLogin.setText("FaculRide🚗");

        LblEmail.setText("Email:");

        Text2.addActionListener(this::Text2ActionPerformed);

        LblSenha.setText("Senha:");

        Text1.addActionListener(this::Text1ActionPerformed);

        BtEntrar.setBackground(new java.awt.Color(204, 204, 255));
        BtEntrar.setText("Entrar");
        BtEntrar.addActionListener(this::BtEntrarActionPerformed);

        LblConta.setText("Não possui conta?");

        BtCadastrar.setBackground(new java.awt.Color(204, 204, 255));
        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(this::BtCadastrarActionPerformed);

        LblBem.setFont(new java.awt.Font("Segoe UI Historic", 2, 12)); // NOI18N
        LblBem.setText("Bem vindo!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblConta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblEmail)
                                    .addComponent(LblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtCadastrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtEntrar)
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(FormLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblBem, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblBem)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblEmail)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSenha))
                .addGap(18, 18, 18)
                .addComponent(BtEntrar)
                .addGap(23, 23, 23)
                .addComponent(LblConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text1ActionPerformed

    private void BtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEntrarActionPerformed
        entrar();
    }//GEN-LAST:event_BtEntrarActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
        FormTelaCadastro.getFormTelaCadastro().setVisible(true);
    }//GEN-LAST:event_BtCadastrarActionPerformed
    private void limparCampos() {
    Text1.setText("");
    Text2.setText("");
} 
    
    private void entrar() {

   UsuarioController controller =
        new UsuarioController();

Usuario usuario =
        controller.login(
        Text1.getText(),
        Text2.getText()
        );

if (usuario != null) {
     sessao.usuarioLogado = usuario;
     System.out.println(
    "Usuário logado: "
    + sessao.usuarioLogado.getNome()
     );

     System.out.println(
    "Email: "
    + sessao.usuarioLogado.getEmail()
     );
    JOptionPane.showMessageDialog(
            null,
            "Login realizado com sucesso!"
    );

    FormTelaHome.getFormTelaHome().setVisible(true);
    this.dispose();

} else {

    JOptionPane.showMessageDialog(
            null,
            "E-mail ou senha inválidos!"
    );

    limparCampos();
 }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtEntrar;
    private javax.swing.JLabel FormLogin;
    private javax.swing.JLabel LblBem;
    private javax.swing.JLabel LblConta;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblSenha;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    // End of variables declaration//GEN-END:variables
}
