/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculride.view;
import com.mycompany.faculride.controller.AvaliacaoController;
import com.mycompany.faculride.controller.CaronaController;
import com.mycompany.faculride.controller.SolicitacaoController;
import com.mycompany.faculride.model.Solicitacao;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.sessao;
/**
 *
 * @author livia
 */
public class FormCaronasDisponiveis extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCaronasDisponiveis.class.getName());
    private static FormCaronasDisponiveis FormCaronasDisponiveisUnico;

    
    private FormCaronasDisponiveis() {
        initComponents();
        carregarTabela();
    }

    
    // MÉTODO SINGLETON
    public static FormCaronasDisponiveis getFormCaronasDisponiveis() {
        if (FormCaronasDisponiveisUnico == null) {
            FormCaronasDisponiveisUnico =
            new FormCaronasDisponiveis();
        }
        return FormCaronasDisponiveisUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCarona = new javax.swing.JTable();
        BtSolicitar = new javax.swing.JButton();
        LblInicio = new javax.swing.JLabel();
        BtHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblLogo.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        LblLogo.setText("Caronas Disponíveis🚗");

        TableCarona.setAutoCreateRowSorter(true);
        TableCarona.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        TableCarona.setForeground(new java.awt.Color(102, 102, 255));
        TableCarona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome Motorista", "Avaliação", "Origem", "Destino", "Horário", "Valor", "Status"
            }
        ));
        TableCarona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCaronaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCarona);

        BtSolicitar.setBackground(new java.awt.Color(204, 204, 255));
        BtSolicitar.setText("Solicitar Carona");
        BtSolicitar.addActionListener(this::BtSolicitarActionPerformed);

        LblInicio.setText("Volte para a tela inicial...");

        BtHome.setBackground(new java.awt.Color(204, 204, 255));
        BtHome.setText("Home");
        BtHome.addActionListener(this::BtHomeActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 325, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtSolicitar)
                        .addGap(325, 325, 325))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(LblInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(BtHome)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LblLogo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BtSolicitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(LblInicio)
                .addGap(5, 5, 5)
                .addComponent(BtHome)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSolicitarActionPerformed
       solicitarCarona();
    }//GEN-LAST:event_BtSolicitarActionPerformed

    private void TableCaronaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCaronaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableCaronaMouseClicked

    private void BtHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHomeActionPerformed
        FormTelaHome.getFormTelaHome().setVisible(true);
    }//GEN-LAST:event_BtHomeActionPerformed
private void carregarTabela() {

    DefaultTableModel modelo =
        (DefaultTableModel)
        TableCarona.getModel();

    modelo.setRowCount(0);

    CaronaController controller =
        new CaronaController();

    AvaliacaoController avaliacaoController =
        new AvaliacaoController();

    try {

        ResultSet rs =
            controller.listarCaronas();

        while (rs.next()) {

            String motorista =
                rs.getString(
                    "motorista"
                );

            double media =
                avaliacaoController
                .calcularMedia(
                    motorista
                );

            modelo.addRow(
                new Object[] {
                    rs.getInt("id"),

                    motorista,

                    String.format(
                        "%.1f",
                        media
                    ),

                    rs.getString(
                        "origem"
                    ),

                    rs.getString(
                        "destino"
                    ),

                    rs.getString(
                        "horario"
                    ),

                    rs.getDouble(
                        "valor"
                    ),

                    rs.getString(
                        "status"
                    )
                }
            );
        }

    } catch (Exception e) {

        e.printStackTrace();
    }
}

private void solicitarCarona() {

    int linha =
        TableCarona.getSelectedRow();

    if (linha == -1) {

        JOptionPane.showMessageDialog(
            null,
            "Selecione uma carona!"
        );

        return;
    }

    int idCarona =
        Integer.parseInt(
            TableCarona.getValueAt(
                linha,
                0
            ).toString()
        );

    String motorista =
        TableCarona.getValueAt(
            linha,
            1
        ).toString();

    Solicitacao solicitacao =
        new Solicitacao();

    solicitacao.setPassageiro(
        sessao.usuarioLogado.getNome()
    );

    solicitacao.setMotorista(
        motorista
    );

    solicitacao.setStatus(
        "Pendente"
    );

    solicitacao.setId_carona(
        idCarona
    );

    SolicitacaoController controller =
        new SolicitacaoController();

    controller.solicitarVaga(
        solicitacao
    );

    JOptionPane.showMessageDialog(
        null,
        "Solicitação enviada com sucesso!"
    );
}
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtHome;
    private javax.swing.JButton BtSolicitar;
    private javax.swing.JLabel LblInicio;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JTable TableCarona;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
