/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculride.view;

import javax.swing.JOptionPane;
import util.sessao;

/**
 *
 * @author livia
 */
public class FormTelaHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTelaHome.class.getName());
    private static FormTelaHome formTelaHomeUnico;

    
    private FormTelaHome() {
        initComponents();
    }

    
    // MÉTODO SINGLETON
    public static FormTelaHome getFormTelaHome() {
        if (formTelaHomeUnico == null) {
            formTelaHomeUnico =
            new FormTelaHome();
        }
        return formTelaHomeUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        LblBem = new javax.swing.JLabel();
        LblLogo = new javax.swing.JLabel();
        LblAcoes = new javax.swing.JLabel();
        BtOferecer = new javax.swing.JButton();
        BtVer = new javax.swing.JButton();
        MenuPrincipal = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        Menu2 = new javax.swing.JMenu();
        Menu3 = new javax.swing.JMenu();
        Menu4 = new javax.swing.JMenu();
        Menu5 = new javax.swing.JMenu();
        Menu6 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblBem.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        LblBem.setText("Olá, Seja bem vindo");

        LblLogo.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        LblLogo.setForeground(new java.awt.Color(102, 102, 255));
        LblLogo.setText("FaculRide🚗");

        LblAcoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LblAcoes.setText("Ações Rápidas:");

        BtOferecer.setForeground(new java.awt.Color(102, 102, 255));
        BtOferecer.setText("+  Oferecer Carona");
        BtOferecer.addActionListener(this::BtOferecerActionPerformed);

        BtVer.setForeground(new java.awt.Color(102, 102, 255));
        BtVer.setText("🔍 ver caronas disponiveis");
        BtVer.addActionListener(this::BtVerActionPerformed);

        Menu1.setBackground(new java.awt.Color(204, 204, 255));
        Menu1.setText("🏠 Home");
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu1MouseClicked(evt);
            }
        });
        MenuPrincipal.add(Menu1);

        Menu2.setText("👥 Oferecer Carona");
        Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu2MouseClicked(evt);
            }
        });
        MenuPrincipal.add(Menu2);

        Menu3.setText("🚗 Caronas disponíveis");
        Menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu3MouseClicked(evt);
            }
        });
        MenuPrincipal.add(Menu3);

        Menu4.setText("✉️ Solicitações");
        Menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu4MouseClicked(evt);
            }
        });
        MenuPrincipal.add(Menu4);

        Menu5.setText("★Avaliação");
        Menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu5MouseClicked(evt);
            }
        });
        MenuPrincipal.add(Menu5);

        Menu6.setText("👥Login");
        Menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu6MouseClicked(evt);
            }
        });
        MenuPrincipal.add(Menu6);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LblBem)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(LblAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(BtOferecer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(BtVer)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblBem)
                .addGap(34, 34, 34)
                .addComponent(LblAcoes)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtOferecer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtVer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtOferecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtOferecerActionPerformed
        FormOferecerCarona.getFormOferecerCarona().setVisible(true);
    }//GEN-LAST:event_BtOferecerActionPerformed

    private void BtVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVerActionPerformed
        FormCaronasDisponiveis.getFormCaronasDisponiveis().setVisible(true);
    }//GEN-LAST:event_BtVerActionPerformed

    private void Menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu1MouseClicked

    private void Menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseClicked
        FormOferecerCarona.getFormOferecerCarona().setVisible(true);
    }//GEN-LAST:event_Menu2MouseClicked

    private void Menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseClicked
        FormCaronasDisponiveis.getFormCaronasDisponiveis().setVisible(true);
    }//GEN-LAST:event_Menu3MouseClicked

    private void Menu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseClicked
        FormSolicitacoes.getFormSolicitacoes().setVisible(true);
    }//GEN-LAST:event_Menu4MouseClicked

    private void Menu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseClicked
        FormAvaliacao.getFormAvaliacao().setVisible(true);
    }//GEN-LAST:event_Menu5MouseClicked

    private void Menu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MouseClicked
        logout();
    }//GEN-LAST:event_Menu6MouseClicked
    private void logout() {

    int opcao =
        JOptionPane.showConfirmDialog(
            null,
            "Deseja realmente sair?",
            "Logout",
            JOptionPane.YES_NO_OPTION
        );

    if (opcao == JOptionPane.YES_OPTION) {

        sessao.usuarioLogado = null;

        this.dispose();

        new FormTelaLogin()
            .setVisible(true);
    }
}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtOferecer;
    private javax.swing.JButton BtVer;
    private javax.swing.JLabel LblAcoes;
    private javax.swing.JLabel LblBem;
    private javax.swing.JLabel LblLogo;
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenu Menu2;
    private javax.swing.JMenu Menu3;
    private javax.swing.JMenu Menu4;
    private javax.swing.JMenu Menu5;
    private javax.swing.JMenu Menu6;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    // End of variables declaration//GEN-END:variables
}
