/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculride.view;

import com.mycompany.faculride.controller.UsuarioController;
import com.mycompany.faculride.model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author livia
 */
public class FormTelaCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTelaCadastro.class.getName());
     private static FormTelaCadastro formTelaCadastroUnico;

    
    private FormTelaCadastro() {
        initComponents();
    }

    
    // MÉTODO SINGLETON
    public static FormTelaCadastro
    getFormTelaCadastro() {
        if (formTelaCadastroUnico == null) {
            formTelaCadastroUnico =
            new FormTelaCadastro();
        }
        return formTelaCadastroUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormCadastro = new javax.swing.JLabel();
        LdlNome = new javax.swing.JLabel();
        TextCad1 = new javax.swing.JTextField();
        LdlEmail = new javax.swing.JLabel();
        TextCad2 = new javax.swing.JTextField();
        LdlCurso = new javax.swing.JLabel();
        TextCad3 = new javax.swing.JTextField();
        LdlSenha = new javax.swing.JLabel();
        LdlConfirm = new javax.swing.JLabel();
        TextCad5 = new javax.swing.JTextField();
        BtCad = new javax.swing.JButton();
        TextCad4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtCad1 = new javax.swing.JButton();
        BtCad2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FormCadastro.setFont(new java.awt.Font("Serif", 2, 24)); // NOI18N
        FormCadastro.setText("Criar Conta 👥");

        LdlNome.setText("Nome Completo:");

        LdlEmail.setText("Email:");

        TextCad2.addActionListener(this::TextCad2ActionPerformed);

        LdlCurso.setText("Curso:");

        LdlSenha.setText("Senha:");

        LdlConfirm.setText("Confirmar Senha:");

        TextCad5.addActionListener(this::TextCad5ActionPerformed);

        BtCad.setBackground(new java.awt.Color(204, 204, 255));
        BtCad.setText("Cadastrar");
        BtCad.addActionListener(this::BtCadActionPerformed);

        TextCad4.addActionListener(this::TextCad4ActionPerformed);

        jLabel1.setText("Já possui conta?");

        BtCad1.setBackground(new java.awt.Color(204, 204, 255));
        BtCad1.setText("Login");
        BtCad1.addActionListener(this::BtCad1ActionPerformed);

        BtCad2.setBackground(new java.awt.Color(204, 204, 255));
        BtCad2.setText("Limpar");
        BtCad2.addActionListener(this::BtCad2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LdlConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LdlEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LdlCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LdlNome)
                                    .addComponent(LdlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextCad1)
                                    .addComponent(TextCad3)
                                    .addComponent(TextCad5)
                                    .addComponent(TextCad4, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                    .addComponent(TextCad2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtCad)
                                .addGap(117, 117, 117)))
                        .addGap(188, 188, 188))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtCad1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtCad2)
                        .addGap(106, 106, 106))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FormCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(FormCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LdlNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LdlEmail)
                    .addComponent(TextCad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LdlCurso)
                    .addComponent(TextCad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LdlSenha))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LdlConfirm)
                    .addComponent(TextCad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BtCad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCad1)
                    .addComponent(BtCad2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCad2ActionPerformed

    private void TextCad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCad5ActionPerformed

    private void BtCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadActionPerformed
        cadastrarUsuario();        
    }//GEN-LAST:event_BtCadActionPerformed

    private void TextCad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCad4ActionPerformed

    private void BtCad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCad1ActionPerformed
        FormTelaLogin.getFormTelaLogin().setVisible(true);
    }//GEN-LAST:event_BtCad1ActionPerformed

    private void BtCad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCad2ActionPerformed
        limparCampos();
    }//GEN-LAST:event_BtCad2ActionPerformed
private void limparCampos() {
    TextCad1.setText("");
    TextCad2.setText("");
    TextCad3.setText("");
    TextCad4.setText("");
    TextCad5.requestFocus();
    }
private void cadastrarUsuario() {
    
      if (TextCad1.getText().isEmpty()
            || TextCad2.getText().isEmpty()
            || TextCad3.getText().isEmpty()
            || TextCad4.getText().isEmpty()) {

        JOptionPane.showMessageDialog(
                null,
                "Preencha todos os campos!"
        );

        return;
    }

    Usuario usuario = new Usuario();

    usuario.setNome(
        TextCad1.getText()
    );

    usuario.setEmail(
        TextCad4.getText()
    );

    usuario.setCurso(
        TextCad3.getText()
    );
    
    usuario.setSenha(
        TextCad2.getText()
    );


    UsuarioController controller =
    new UsuarioController();

    controller.cadastrarUsuario(
        usuario
    );

    JOptionPane.showMessageDialog(
        null,
        "Usuário cadastrado!"
    );
    
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCad;
    private javax.swing.JButton BtCad1;
    private javax.swing.JButton BtCad2;
    private javax.swing.JLabel FormCadastro;
    private javax.swing.JLabel LdlConfirm;
    private javax.swing.JLabel LdlCurso;
    private javax.swing.JLabel LdlEmail;
    private javax.swing.JLabel LdlNome;
    private javax.swing.JLabel LdlSenha;
    private javax.swing.JTextField TextCad1;
    private javax.swing.JTextField TextCad2;
    private javax.swing.JTextField TextCad3;
    private javax.swing.JTextField TextCad4;
    private javax.swing.JTextField TextCad5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
